#!/bin/bash
# This script will correctly start the QEWD Container in debug/shell mode
#
#
# Run this startup script from the '~/qewd-baseline' folder
#  (or whatever you've renamed it) using:
#
#     ./start_debug
#
echo 'Starting qewd container in debug/shell mode'
echo ' '
echo 'From the QEWD Container shell, start QEWD using:'
echo ' '
echo '  node qewd'
docker run -it --name qewd --rm --network qewd-net -p 8080:8080 -p 9229:9229 -v /home/rsr/Documents/qewd-baseline:/opt/qewd/mapped --entrypoint=/bin/bash rtweed/qewd-server