#!/bin/bash
# This script will correctly start the QEWD Container
#
#
# Run this startup script from the '~/qewd-baseline' folder
#  (or whatever you've renamed it) using:
#
#     - with persistence:    ./start_p
#     - without persistence: ./start
#
echo 'Starting qewd container'
docker run -d --name qewd --rm --network qewd-net -p 8080:8080 -v /home/rsr/Documents/qewd-baseline:/opt/qewd/mapped  rtweed/qewd-server
echo 'qewd Container has been started'