#!/bin/bash
# This script will cleanly stop the qewd Container by issuing a command to QEWD to stop
#
#
# Run this shutdown script from the '~/qewd-baseline' folder
#  (or whatever you've renamed it) using:
#
#     ./stop
#
echo 'Stopping qewd Container'
#
#  Send authenticated requests to cleanly shut down QEWD Containers
#
docker run -it --name qewd_shutdown --rm --network qewd-net -v $PWD:/node -e "node_script=shutdown" rtweed/node-runner